on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'xiph/flac'
          path: flac
      - uses: actions/checkout@v2
        with:
          repository: 'xiph/ogg'
          path: ogg
      - run: cmake .

      - if: ${{ runner.os == 'Linux'}}
        run: make
      - if: ${{ runner.os == 'Windows'}}
        run: msbuild
      - if: ${{ runner.os == 'macOS'}}
        run: xcodebuild


      
